version: "3.5"
services:
  web:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./project:/home/node/app
    ports:
      - "3333:3000"
    command: "npm run start:dev"
    networks:
      - frontend
networks:
  frontend:
    name: blog_frontend
    driver: bridge
