import Color from "color";
const PRIMARY = "#0CA461";
const PRIMARY_DARK = Color("#1D7B59")
  .alpha(0.8)
  .lighten(0.01);
const PRIMARY_LIGHT = Color(PRIMARY).lighten(0.04);
const BACKGROUND = "#EAEAEA";
const TEXT_LIGHT = "#FFF";
const TEXT_LIGHT_PRIMARY = Color(TEXT_LIGHT).alpha(0.87);
const TEXT_LIGHT_SECONDARY = Color(TEXT_LIGHT).alpha(0.64);
const TEXT_LIGHT_HINT = Color(TEXT_LIGHT).alpha(0.54);
const TEXT_LIGHT_DISABLED = Color(TEXT_LIGHT).alpha(0.38);
const TEXT_DARK = "#000";
const TEXT_DARK_PRIMARY = Color(TEXT_DARK).alpha(0.87);
const TEXT_DARK_SECONDARY = Color(TEXT_DARK).alpha(0.64);
const TEXT_DARK_HINT = Color(TEXT_DARK).alpha(0.54);
const TEXT_DARK_DISABLED = Color(TEXT_DARK).alpha(0.38);
const WHITE = "#FFF";
const BLACK = "#000";
export default {
  PRIMARY,
  PRIMARY_DARK,
  PRIMARY_LIGHT,
  BACKGROUND,
  TEXT_LIGHT,
  TEXT_LIGHT_PRIMARY,
  TEXT_LIGHT_SECONDARY,
  TEXT_LIGHT_HINT,
  TEXT_LIGHT_DISABLED,
  TEXT_DARK,
  TEXT_DARK_PRIMARY,
  TEXT_DARK_SECONDARY,
  TEXT_DARK_HINT,
  TEXT_DARK_DISABLED,
  WHITE,
  BLACK
};
