const COMMON_MARGINN = 10;
const COMMON_PADDING = 10;
const COMMON_RADIUS = 4;
const TEXT_PRIMARY = 16;
const TEXT_SECONDARY = 12;
const TEXT_HINT = 10;

export default {
  COMMON_MARGINN,
  COMMON_PADDING,
  COMMON_RADIUS,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_HINT
};
