// margin
const MARGIN_MOBILE = 16;
const MARGIN_TABLE_OR_DESKTOP = 24;
// break points
const BREAK_POINT_SMALL_HANDSET = 360;
const BREAK_POINT_MEDIUM_HANDSET = 400;
const BREAK_POINT_LARGE_HANDSET = 600;
const BREAK_POINT_SMALL_TABLE = 720;
const BREAK_POINT_MEDIUM_TABLE = 840;
const BREAK_POINT_LARGE_TABLE = 960;
const BREAK_POINT_SMALL_DESKTOP = 1024;
const BREAK_POINT_MEDIUM_DESKTOP = 1280;
const BREAK_POINT_LARGE_DESKTOP = 1440;
// break points columns
const BREAK_POINT_SMALL_HANDSET_COLUMNS = 4;
const BREAK_POINT_MEDIUM_HANDSET_COLUMNS = 4;
const BREAK_POINT_LARGE_HANDSET_COLUMNS = 4;
const BREAK_POINT_SMALL_TABLE_COLUMNS = 4;
const BREAK_POINT_MEDIUM_TABLE_COLUMNS = 8;
const BREAK_POINT_LARGE_TABLE_COLUMNS = 8;
const BREAK_POINT_SMALL_DESKTOP_COLUMNS = 12;
const BREAK_POINT_MEDIUM_DESKTOP_COLUMNS = 12;
const BREAK_POINT_LARGE_DESKTOP_COLUMNS = 12;
// break points gutters
const BREAK_POINT_SMALL_HANDSET_GUTTERS = 16;
const BREAK_POINT_MEDIUM_HANDSET_GUTTERS = 16;
const BREAK_POINT_LARGE_HANDSET_GUTTERS = 16;
const BREAK_POINT_SMALL_TABLE_GUTTERS = 16;
const BREAK_POINT_MEDIUM_TABLE_GUTTERS = 24;
const BREAK_POINT_LARGE_TABLE_GUTTERS = 24;
const BREAK_POINT_SMALL_DESKTOP_GUTTERS = 24;
const BREAK_POINT_MEDIUM_DESKTOP_GUTTERS = 24;
const BREAK_POINT_LARGE_DESKTOP_GUTTERS = 24;
export default {
  MARGIN_MOBILE,
  MARGIN_TABLE_OR_DESKTOP,
  BREAK_POINT_SMALL_HANDSET,
  BREAK_POINT_MEDIUM_HANDSET,
  BREAK_POINT_LARGE_HANDSET,
  BREAK_POINT_SMALL_TABLE,
  BREAK_POINT_MEDIUM_TABLE,
  BREAK_POINT_LARGE_TABLE,
  BREAK_POINT_SMALL_DESKTOP,
  BREAK_POINT_MEDIUM_DESKTOP,
  BREAK_POINT_LARGE_DESKTOP,
  BREAK_POINT_SMALL_HANDSET_COLUMNS,
  BREAK_POINT_MEDIUM_HANDSET_COLUMNS,
  BREAK_POINT_LARGE_HANDSET_COLUMNS,
  BREAK_POINT_SMALL_TABLE_COLUMNS,
  BREAK_POINT_MEDIUM_TABLE_COLUMNS,
  BREAK_POINT_LARGE_TABLE_COLUMNS,
  BREAK_POINT_SMALL_DESKTOP_COLUMNS,
  BREAK_POINT_MEDIUM_DESKTOP_COLUMNS,
  BREAK_POINT_LARGE_DESKTOP_COLUMNS,
  BREAK_POINT_SMALL_HANDSET_GUTTERS,
  BREAK_POINT_MEDIUM_HANDSET_GUTTERS,
  BREAK_POINT_LARGE_HANDSET_GUTTERS,
  BREAK_POINT_SMALL_TABLE_GUTTERS,
  BREAK_POINT_MEDIUM_TABLE_GUTTERS,
  BREAK_POINT_LARGE_TABLE_GUTTERS,
  BREAK_POINT_SMALL_DESKTOP_GUTTERS,
  BREAK_POINT_MEDIUM_DESKTOP_GUTTERS,
  BREAK_POINT_LARGE_DESKTOP_GUTTERS
};
